### PR TITLE
Add the symfony/monolog-bundle dependency to the standard edition instead of the bundle-cms package

### PR DESCRIPTION
**Pull request by acrobat**
Follow up PR for Kunstmaan/KunstmaanBundlesCMS#2061

### CODE REVIEW

**Comment by acrobat** [comment]
@sandergo90 I've rebased this PR. To make sure `composer update` would work I needed to add some extra dev dependencies. I will create a separate PR to the bundles to add those to the `UPGRADE-5.2` doc.

**Comment by sandergo90** [comment]
@acrobat can you check failing build?

**Comment by acrobat** [comment]
The bundles package was still some commits behind, should be fixed now!

**Comment by acrobat** [comment]
Build failure should be fixed after #2193 is merged

**Pull request merged**
